### ISSUE TITLE
Is posible to add image, logo to report?

### ISSUE THREAD

**Issue by tudorels** [ankareport/ankareport#8]
Hello,
I just found your reporting tool and I think is great. I wonder if it's posible to add image to report?
Thank you!

**Comment by metiftikci** [comment]
hi @tudorels currently only text supported

**Comment by tudorels** [comment]
Thank you! Maybe in the future ...

**Comment by metiftikci** [comment]
@tudorels you can check `feat-image` branch. i tried to implement it but wont merge now. it requires some refactors.

you should set source as base64 string like `data:image/png;base64,iVBORw0...` or a `url` which is same with src attribute of img element

> ❗**It is a breaking change ❗

layout items requires `type` value as `text` or `image`

https://github.com/ankareport/ankareport/commit/253367b62dd04d447037ca10049a20a7cc0fdf8d#diff-2104e1199ab73b0054c8566326bd77d287649a603f12f4be1df339209a624ce7L4-L9

**Comment by metiftikci** [comment]
It's now released. you can check the [playground](https://ankareport.js.org/examples/playground/) page

**Comment by tudorels** [comment]
Thank you! A very useful option that I needed. Keep up the good stuff!
